GET https://hcateringback-dev.unitbeandev.com/api/wh/items?page=3&pageSize=20&itemName=1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxMzY0NjgwMH0.NzTgxdETSrAQvjUD-gh4H9Ve2LUKOPDTo7lJo1i-dcvsRRxNjNWBFtFdgiPLvxxhMQS-nSbHLS3vMyxTL1eWjQ

###

GET https://hcateringback-dev.unitbeandev.com/api/wh/items?page=3&pageSize=20&sortOrder=ASC
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxMzY0NjgwMH0.NzTgxdETSrAQvjUD-gh4H9Ve2LUKOPDTo7lJo1i-dcvsRRxNjNWBFtFdgiPLvxxhMQS-nSbHLS3vMyxTL1eWjQ

###

POST https://hcateringback-dev.unitbeandev.com/api/auth/login
Content-Type: application/json

{
    "login": "admin",
    "password": "admin"
}